### ISSUE TITLE
Wallet Connect

### ISSUE THREAD

**Issue by GORILLASTIXS** [Vytek/AlgorandUnitySDK#1]
Hello, 
What is the best way to integrate wallet connect in the scenes? Should I add it in the startgame.cs or algorandmanager.cs? Please help! Thank you in advance.Best, GorillaStixs.

**Comment by Vytek** [comment]
I am sorry but I not have time to add this feature. It is a quick and dirty SDK. We had to study https://github.com/WalletConnect/WalletConnectSharp and try to include and use it in my project. It is not easy ;-) Try other official SDK: https://github.com/CareBoo/unity-algorand-sdk

**Comment by GORILLASTIXS** [comment]
Thank you!
