### ISSUE TITLE
Algorand Manager Does not Start

### ISSUE THREAD

**Issue by GORILLASTIXS** [Vytek/AlgorandUnitySDK#2]
Hello - When I create a build of the scenes, the Algorand Manager does not start up. Do you have any recommendations on how to resolve the issue?

**Comment by Vytek** [comment]
Has Algorand Manager been inserted into a GamaObject in the scene? I tried to build all the scenes in the examples and they all work fine. Try to do a Development Build and then read in the LOG what is happening.
